function createfigure(X1, YMatrix1)
%CREATEFIGURE(X1, YMATRIX1)
%  X1:  vector of x data
%  YMATRIX1:  matrix of y data

%  Auto-generated by MATLAB on 11-Nov-2019 09:08:43

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1,...
    'Position',[0.13 0.24822695035461 0.407488708220416 0.67677304964539]);
hold(axes1,'on');

% Create multiple lines using matrix input to plot
plot1 = plot(X1,YMatrix1,'LineWidth',1.5,'Parent',axes1);
set(plot1(1),'DisplayName','10kbaud channel, no noise',...
    'Color',[0 0.447058826684952 0.74117648601532]);
set(plot1(2),'DisplayName','10kbaud channel, 50% bus load',...
    'Color',[0.301960796117783 0.745098054409027 0.933333337306976]);
set(plot1(3),'DisplayName','100kbaud channel, no noise',...
    'Color',[0 0.498039215803146 0]);
set(plot1(4),'DisplayName','100kbaud channel, 50% bus load',...
    'Color',[0.749019622802734 0.749019622802734 0]);

% Create xlabel
xlabel({'\delta offset [ms]'},'FontWeight','bold','FontSize',14);

% Create ylabel
ylabel({'Correct/total transmission ratio'},'FontWeight','bold',...
    'FontSize',14);

box(axes1,'on');
% Set the remaining axes properties
set(axes1,'FontSize',12,'XDir','reverse','XTick',[2 3 4 5 6 7]);
% Create legend
legend1 = legend(axes1,'show');
set(legend1,...
    'Position',[0.143405600722674 0.283687943262411 0.185185185185185 0.121749408983452]);

